classdef COMSOLdCutPlane < handle
    % COMSOLdCutPlane - cut planes saved from COMSOLd job.
    %
    % This object is generated by a COMSOLdResults object via the
    % getCutPlane method.
    %
    % Because there is a seperate cut plane for each frequency in the study
    % this class only presents a single cut plane at a time.  Like with
    % the COMSOLdResults class you can step through the frequencies with
    % similar methods as explained in that class file.
    %
    % Data is accessed through the getField method:
    %
    % cut_plane.getField("Ex")
    %
    % for example returns and array of the x component of the E field at  
    % the current frequency, and so on. Obviously you need to modify this 
    % class file to match the cut plane files that your comsol file 
    % outputs.
    %
    % The method
    %
    % cut_plane.getPartField("Ex", x_range, y_range)
    %
    % returns only a portion of the cut plane, with x_range and y_range
    % being indexes into the array.
    %
    
    properties (SetAccess='private')
        % where the completed job scripts are stored.
        jobs_dir = 'C:\Users\matthew\MATLAB Drive\COMSOL\jobs\completed\';
        
        % Change the path temprorarily to add these directories where the
        % function scripts are kept.
        COMSOL_dir = {'C:\Users\matthew\MATLAB Drive\COMSOL\', ...
            'C:\Users\matthew\MATLAB Drive\COMSOL\COMSOLd\', ...
            'C:\Users\matthew\MATLAB\Projects\COMSOLd\config\', ...
            'C:\Users\matthew\MATLAB\Projects\COMSOLd\post_processing\'};
        
        % The options struct defined by the job script.
        options;
       
        % Data
        x;
        y;
        
        Ex;
        Ey;
        Ez;
        relEx;
        relEy;
        relEz;
         
        Hx;
        Hy;
        Hz;
        relHx;
        relHy;
        relHz;
        
        % Which frequency are we looking at
        freq_num;
        
        % Whether we are stepping through frequencies
        stepping_through_freqs;
    end
    
    methods
        %%
        %
        % SETUP functions
        %
        function hObj = COMSOLdCutPlane(options, cut_plane_in)
            
            hObj.options = options;
            hObj.freq_num = 1;
            hObj.stepping_through_freqs = false;
            
            hObj.x = cut_plane_in{1}.cut_plane.x;
            hObj.y = cut_plane_in{1}.cut_plane.y;

            hObj.Ex = reshape(cut_plane_in{1}.cut_plane.ewfd_Ex, ...
                [length(unique(hObj.x)) length(unique(hObj.y)) size(cut_plane_in{1}.cut_plane.ewfd_Ex, 2)]);
            hObj.Ey = reshape(cut_plane_in{1}.cut_plane.ewfd_Ey, ...
                [length(unique(hObj.x)) length(unique(hObj.y)) size(cut_plane_in{1}.cut_plane.ewfd_Ey, 2)]);
            hObj.Ez = reshape(cut_plane_in{1}.cut_plane.ewfd_Ez, ...
                [length(unique(hObj.x)) length(unique(hObj.y)) size(cut_plane_in{1}.cut_plane.ewfd_Ez, 2)]);
            hObj.relEx = reshape(cut_plane_in{1}.cut_plane.ewfd_relEx, ...
                [length(unique(hObj.x)) length(unique(hObj.y)) size(cut_plane_in{1}.cut_plane.ewfd_relEx, 2)]);
            hObj.relEy = reshape(cut_plane_in{1}.cut_plane.ewfd_relEy, ...
                [length(unique(hObj.x)) length(unique(hObj.y)) size(cut_plane_in{1}.cut_plane.ewfd_relEy, 2)]);
            hObj.relEz = reshape(cut_plane_in{1}.cut_plane.ewfd_relEz, ...
                [length(unique(hObj.x)) length(unique(hObj.y)) size(cut_plane_in{1}.cut_plane.ewfd_relEz, 2)]);

            hObj.Hx = reshape(cut_plane_in{2}.cut_plane.ewfd_Hx, ...
                [length(unique(hObj.x)) length(unique(hObj.y)) size(cut_plane_in{2}.cut_plane.ewfd_Hx, 2)]);
            hObj.Hy = reshape(cut_plane_in{2}.cut_plane.ewfd_Hy, ...
                [length(unique(hObj.x)) length(unique(hObj.y)) size(cut_plane_in{2}.cut_plane.ewfd_Hy, 2)]);
            hObj.Hz = reshape(cut_plane_in{2}.cut_plane.ewfd_Hz, ...
                [length(unique(hObj.x)) length(unique(hObj.y)) size(cut_plane_in{2}.cut_plane.ewfd_Hz, 2)]);
            hObj.relHx = reshape(cut_plane_in{2}.cut_plane.ewfd_relHx, ...
                [length(unique(hObj.x)) length(unique(hObj.y)) size(cut_plane_in{2}.cut_plane.ewfd_relHx, 2)]);
            hObj.relHy = reshape(cut_plane_in{2}.cut_plane.ewfd_relHy, ...
                [length(unique(hObj.x)) length(unique(hObj.y)) size(cut_plane_in{2}.cut_plane.ewfd_relHy, 2)]);
            hObj.relHz = reshape(cut_plane_in{2}.cut_plane.ewfd_relHz, ...
                [length(unique(hObj.x)) length(unique(hObj.y)) size(cut_plane_in{2}.cut_plane.ewfd_relHz, 2)]);
        
        end
      
        %%
        % 
        % Methods to access data
        %
        
        
        % How many freqs are there?
        %
        function out = numFreqs(hObj)
            out = size(hObj.Ex, 3);
        end
        
        % Is there another study in the sweep?
        %
        function out = moreFreqs(hObj)
            % If we are on the last study, so there is no next study
            if hObj.freq_num == hObj.numFreqs()
                out = false;
            else
                out = true;
            end
        end
        
        % Is there a previous study in the sweep?
        %
        function out = earlierFreqs(hObj)
            % If we are on the first study, so there is no previous study
            if hObj.freq_num == 1
                out = false;
            else
                out = true;
            end
        end
        
        % Move a particular study
        %
        function setFreq(hObj, num)
            % The requested study does not exist
            if num < 1 || num > hObj.numFreqs()
                error("Requested frequency number %d but there are only %d studies", num, hObj.numFreqs());
            else
                hObj.freq_num = num;
            end
        end
        
        % Move to the next study
        %
        function nextFreq(hObj)
            % If we are on the last study, so there is no next study
            if ~hObj.moreFreqs()
                error("No next frequency");
            else
                hObj.setFreq(hObj.freq_num + 1);
            end
        end
        
        % Move to the previous study
        %
        function previousFreq(hObj)
            if ~hObj.earlierFreqs()
                error("No previous frequency");
            else
                hObj.setFreq(hObj.freq_num - 1);
            end
        end
        
        % Move to the first study
        %
        function firstFreq(hObj)
            hObj.setFreq(1);
        end
        
        % Move to the last study
        %
        function lastFreq(hObj)
            hObj.setFreq(hObj.numFreqs());
        end
        
        
        % Step through the frequencies one at a time
        %
        function out = stepThroughFrequencies(hObj)
            % If this is the first step
            if ~hObj.stepping_through_freqs
                hObj.stepping_through_freqs = true;
                hObj.firstFreq();
                out = true;
            else
                if hObj.moreFreqs()
                    hObj.nextFreq();
                    out = true;
                else
                    hObj.stepping_through_freqs = false;
                    out = false;
                end
            end
        end
        
        % Only get a field at all frequencies
        function out = getField(hObj, field)
            
            switch lower(field)
                case "ex"
                    out = squeeze(hObj.Ex(:,:,hObj.freq_num));
                case "ey"
                    out = squeeze(hObj.Ey(:,:,hObj.freq_num));
                case "ez"
                    out = squeeze(hObj.Ez(:,:,hObj.freq_num));
                case "relex"
                    out = squeeze(hObj.relEx(:,:,hObj.freq_num));
                case "reley"
                    out = squeeze(hObj.relEy(:,:,hObj.freq_num));
                case "relez"
                    out = squeeze(hObj.relEz(:,:,hObj.freq_num));
                case "hx"
                    out = squeeze(hObj.Hx(:,:,hObj.freq_num));
                case "hy"
                    out = squeeze(hObj.Hy(:,:,hObj.freq_num));
                case "hz"
                    out = squeeze(hObj.Hz(:,:,hObj.freq_num));
                case "relhx"
                    out = squeeze(hObj.relHx(:,:,hObj.freq_num));
                case "relhy"
                    out = squeeze(hObj.relHy(:,:,hObj.freq_num));
                case "relhz"
                    out = squeeze(hObj.relHz(:,:,hObj.freq_num));
                case "poynting"
                    out = squeeze(hObj.Poynting(:,:,hObj.freq_num));
                case "relpoynting"
                    out = squeeze(hObj.relPoynting(:,:,hObj.freq_num));
                otherwise
                    error("Unknown field: %s", field);
            end
        end
        
        % get a subsection of the field at all frequencies
        function out = getPartField(hObj, field, x_range, y_range)
            switch lower(field)
                case "ex"
                    out = squeeze(hObj.Ex(x_range, y_range,hObj.freq_num));
                case "ey"
                    out = squeeze(hObj.Ey(x_range, y_range,hObj.freq_num));
                case "ez"
                    out = squeeze(hObj.Ez(x_range, y_range,hObj.freq_num));
                case "relex"
                    out = squeeze(hObj.relEx(x_range, y_range,hObj.freq_num));
                case "reley"
                    out = squeeze(hObj.relEy(x_range, y_range,hObj.freq_num));
                case "relez"
                    out = squeeze(hObj.relEz(x_range, y_range,hObj.freq_num));
                case "hx"
                    out = squeeze(hObj.Hx(x_range, y_range,hObj.freq_num));
                case "hy"
                    out = squeeze(hObj.Hy(x_range, y_range,hObj.freq_num));
                case "hz"
                    out = squeeze(hObj.Hz(x_range, y_range,hObj.freq_num));
                case "relhx"
                    out = squeeze(hObj.relHx(x_range, y_range,hObj.freq_num));
                case "relhy"
                    out = squeeze(hObj.relHy(x_range, y_range,hObj.freq_num));
                case "relhz"
                    out = squeeze(hObj.relHz(x_range, y_range,hObj.freq_num));
                case "poynting"
                    out = squeeze(hObj.Poynting(x_range, y_range,hObj.freq_num));
                case "relpoynting"
                    out = squeeze(hObj.relPoynting(x_range, y_range,hObj.freq_num));
                otherwise
                    error("Unknown field: %s", field);
            end
        end
    end
end

