function COMSOL_dir = get_COMSOL_dir
   COMSOL_dir = {'C:\Users\matthew\MATLAB Drive\COMSOL\', ...
            ... 'C:\Users\matthew\MATLAB Drive\COMSOL\COMSOLd\', ...
            'C:\Users\matthew\MATLAB\COMSOLd\utils\', ...
            'C:\Users\matthew\MATLAB\COMSOLd\post_processing\'};
end